dist: bionic
language: python
python:
  - "3.7"
install:
  - pip install poetry
  - poetry install
  - ls -l /run
script:
  - poetry run pytest tests
before_deploy:
  - poetry build -f wheel
  - poetry config repositories.pypi https://pypi.org/simple/
  - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
deploy:
  provider: script
  skip_cleanup: true
  script: poetry publish
